name: auto action runner
run-name: ${{ github.actor }} is running
on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: run
        run: pnpm dev ${{ secrets.SESSION }}
